version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: lomageb-mongo
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: lomageb
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data: 